Repository coenm/RepoM, pull requests merged in 2024-09, with the labels that each got.

#140 Update azure devops pipeline
  .azuredevops/Pipelines/Templates/create-installer.yaml
  .azuredevops/Pipelines/Templates/dotnet-sdk-install.yaml
  .azuredevops/Pipelines/Templates/prepare-code-analysis.yaml
  .azuredevops/Pipelines/Templates/publish-code-analysis.yaml
  .azuredevops/Pipelines/Templates/publish-release-dependencies.yaml
  .azuredevops/Pipelines/build.yaml
  .azuredevops/Pipelines/publish.yaml
  .azuredevops/Pipelines/pull-request.yaml
  .azuredevops/Variables/DotNetSdkVersion.ps1
  .azuredevops/Variables/_all.ps1
  .azuredevops/Variables/_pipelines.ps1
  dotnet-releaser.toml
  mdsnippets.json
Labels: ci

#142 Allow fork based pull requests build in Azure Devops
  .azuredevops/Pipelines/Templates/prepare-code-analysis.yaml
  .azuredevops/Pipelines/Templates/publish-code-analysis.yaml
Labels: ci

#143 Added a mutex to make sure only one instance of RepoM can be running.
  src/RepoM.App/App.xaml.cs
Labels: enhancement

#144 Azure DevOps pipeline task should only run when previous succeeded()
  .azuredevops/Pipelines/Templates/prepare-code-analysis.yaml
  .azuredevops/Pipelines/Templates/publish-code-analysis.yaml
Labels: ci

#149 Update Azure Pipelines to trigger on build tag
  .azuredevops/Pipelines/build.yaml
  .azuredevops/Pipelines/publish.yaml
Labels: ci

#150 Show current version (using nbgv) in help page
  src/RepoM.App/ViewModels/HelpViewModel.cs
Labels: enhancement

#158 Removed fixed path for code and document generation
  src/RepoM.ActionMenu.CodeGen/Program.cs
Labels: enhancement

#159 Fix Azure Dev Ops startup error (Null error check)
  Directory.Build.props
  global.json
  src/RepoM.Plugin.AzureDevOps/Internal/AzureDevOpsPullRequestService.cs
Labels: enhancement

#161 Null Observer Exception
  src/RepoM.Api/Git/DefaultRepositoryMonitor.cs
Labels: bug

#152 Performance improvement of file searching
  src/RepoM.ActionMenu.Core/ActionMenu/Context/FileFunctions.cs
  src/RepoM.App/MainWindow.xaml.cs
  tests/RepoM.ActionMenu.Core.Tests/ActionMenu/Context/FileFunctionsTests.cs
Labels: enhancement

#186 Remove tooltip with 'broken' date
  src/RepoM.Api/Common/HardcodededMiniHumanizer.cs
  src/RepoM.Api/Git/RepositoryViewModel.cs
  src/RepoM.App/Converters/UtcToHumanizedLocalDateTimeConverter.cs
  src/RepoM.App/MainWindow.xaml
  tests/RepoM.Api.Tests/Common/HardcodedMiniHumanizerTests.cs
Labels: bug

#187 Organize repository folders
  .azuredevops/Pipelines/Templates/create-installer.yaml
  README.md
  README.source.md
  _ref/SendKeys.exe
  _ref/libgit2-4aecb64.dylib
  _res/Convert your image to ICO format.url
  _res/Git-Icon-1788C.png
  _res/Icon.svg
  _res/Sized/Icon1024.png
  _res/Sized/Icon128.png
  _res/Sized/Icon16.png
  _res/Sized/Icon256.png
  _res/Sized/Icon32.png
  _res/Sized/Icon512.png
  _res/Sized/Icon64.png
  docs/_old/Ordering.md
  docs/_old/QuickNavigation.gif
  docs/_old/RepoZ-ReadMe-UI-Both.png
  docs/_old/Settings.md
  docs/_old/grr-5fps-compressed.gif
  docs/_old/mdsource/Ordering.source.md
  docs/_old/mdsource/Settings.source.md
  docs/_old/mdsource/_plugin_enable.include.md
  docs/_old/snippets/file.find_files.verified.yaml
  resources/App.ico
  resources/Icon.pdn
  resources/Icon.png
  resources/readme.txt
  setup/RepoM.nsi
  setup/ref/PathEd.exe
  setup/res/modern-wizard.bmp
  setup/res/modern-wizard.pdn
  setup/res/setup.ico
  src/RepoM.ActionMenu.CodeGen/RepoMFolders.cs
Labels: Maintenance

#188 Add support for defining settings folder
  .azuredevops/Pipelines/Templates/create-installer.yaml
  README.md
  README.source.md
  src/RepoM.Api/Bootstrapper.cs
  src/RepoM.Api/IO/AppDataPathConfig.cs
  src/RepoM.Api/IO/AppDataPathProvider.cs
  src/RepoM.Api/IO/DefaultAppDataPathProvider.cs
  src/RepoM.App/App.xaml.cs
  src/RepoM.App/Bootstrapper.cs
  src/RepoM.App/Configuration/Config.cs
  src/RepoM.App/Properties/launchSettings.json
  src/RepoM.App/RepoM.App.csproj
  src/RepoM.App/Services/ConfigBasedAppDataPathProviderFactory.cs
  src/RepoM.App/appsettings.Development.json
  src/RepoM.App/appsettings.json
  tests/RepoM.Api.Tests/IO/AppDataPathProviderTests.cs
  tests/RepoM.App.Tests/BootstrapperTests.cs
  tests/RepoM.App.Tests/ConfigBasedAppDataPathProviderFactoryTest.cs
  tests/SystemTests/AssertionHelper.cs
Labels: feature

#194 TUnit for systemtest
  .azuredevops/Pipelines/build.yaml
  .azuredevops/Pipelines/pull-request.yaml
  tests/SystemTests/DefaultRepositoryMonitorTests.cs
  tests/SystemTests/SystemTests.csproj
Labels: Maintenance

#195 Do not set UseWindowsForms
  src/RepoM.App/RepoM.App.csproj
Labels: Maintenance

#196 Update packages
  src/RepoM.ActionMenu.CodeGen/RepoM.ActionMenu.CodeGen.csproj
  src/RepoM.ActionMenu.Core/RepoM.ActionMenu.Core.csproj
  src/RepoM.Api/RepoM.Api.csproj
  tests/RepoM.ActionMenu.CodeGen.Tests/RepoM.ActionMenu.CodeGen.Tests.csproj
  tests/RepoM.ActionMenu.Core.TestLib/RepoM.ActionMenu.Core.TestLib.csproj
  tests/RepoM.ActionMenu.Core.Tests/RepoM.ActionMenu.Core.Tests.csproj
  tests/RepoM.Api.Tests/RepoM.Api.Tests.csproj
  tests/RepoM.App.Tests/RepoM.App.Tests.csproj
  tests/RepoM.Plugin.AzureDevOps.Tests/RepoM.Plugin.AzureDevOps.Tests.csproj
  tests/RepoM.Plugin.Clipboard.Tests/RepoM.Plugin.Clipboard.Tests.csproj
  tests/RepoM.Plugin.Heidi.Tests/RepoM.Plugin.Heidi.Tests.csproj
  tests/RepoM.Plugin.LuceneQueryParser.Tests/RepoM.Plugin.LuceneQueryParser.Tests.csproj
  tests/RepoM.Plugin.Misc.Tests/RepoM.Plugin.Misc.Tests.csproj
  tests/RepoM.Plugin.SonarCloud.Tests/RepoM.Plugin.SonarCloud.Tests.csproj
  tests/RepoM.Plugin.Statistics.Tests/RepoM.Plugin.Statistics.Tests.csproj
  tests/RepoM.Plugin.WebBrowser.Tests/RepoM.Plugin.WebBrowser.Tests.csproj
  tests/RepoM.Plugin.WindowsExplorerGitInfo.Tests/RepoM.Plugin.WindowsExplorerGitInfo.Tests.csproj
  tests/SystemTests/SystemTests.csproj
Labels: dependencies

#201 Improve message when Scriban cannot execute predicate for context menu
  src/RepoM.ActionMenu.Core/Yaml/Model/Templating/ScribanPredicate.cs
  src/RepoM.ActionMenu.Interface/YamlModel/Templating/Predicate.cs
  src/RepoM.ActionMenu.Interface/YamlModel/Templating/PredicateEvaluationException.cs
  src/RepoM.App/Properties/launchSettings.json
  tests/RepoM.ActionMenu.Core.Tests/Yaml/Model/ScribanPredicateTests.cs
Labels: enhancement
